USE hibernate;

DELETE FROM author2 WHERE id > 6;

ALTER TABLE author2 AUTO_INCREMENT = 6;

-- CREATE DATABASE library;

USE hibernate;

DROP TABLE author2;
DROP TABLE book;

CREATE TABLE author2
(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(45)
);
CREATE TABLE book
(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(45),
    author_id INT(11)
);